# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JwSo/LtN8n4PnrMs7YTINNvGEyyzjy/Orxa1JByuXPlIS3wUbVGQwK01WlsBYf4WRmoB8BBHGZnflqkC0OVywueE8txHiqY/2oeZdU2ehymPCwKDR+O4QIhCxyVKI0F63CAgwoWlpElql+/J6e7H+meRhJpRqdaaN/DWeSJ3Zi3rnD7EMEVIMU5UNC2yernsxafZqWVrb8Z2ZwfS/ajO7X697RAgia2qacwztq1Kz/zy7h/XGBvMtXZfeWoqRr6j1QhcTQLsdc08H6PfZj4jpzxByXvjZVsnpLYC4fhupTmBzq419P0Jih1VCODX5t0nNGfmUwNUzhXVIJw8jcQApawvSxQIfaW7HuQUE/cZWLpECc7fjbuWxrVnGTh6yh/vE6yVDdHNx4/GlvD5QNER/9sw9mWBp+48No89dGV6PVinYpL44DFv/SXSAm0lrYhsMA2lVg+amZeHvtxBuftQg7doMVwVNPn5gZ4/HtrRqYHoWGKS69Di7RgcUW4uLXOFGSMTRuhViZybc5+94yhlDndz58soy9n9cgOdHw4yBMURS6/OEVhHIaVh4vDozIM9jOHaqpqPds6dL3hfx74L9UGBEWZXoEzQ4wol8OZVPuja/aXdGh8zgmvjpmP0kCfD0cN62BxGgcF9MF7kivpvEQz8maIj7d65sBY3kuhbeB4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
